apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.2.4
    chart: redis-cluster
    helm:
      values: |
        image:
          tag: latest
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
