apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: test
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: test
    repoURL: https://github.com/zzxyxy/testclusterconfig.git
    targetRevision: HEAD
  destination:
    namespace: redis-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
