apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.12.1
    chart: apache
    helm:
      values: |
        image:
          tag: 8.12.1
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-staging
            kubernetes.io/ingress.class: ingress
          tls:
            - hosts:
              - test.zxyxy.net
                secretName: test.zxyxy.net-tls
  destination:
    namespace: webapp
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
