apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    argocd.argoproj.io/instance: redis
    redis_setup_type: standalone
    role: standalone
  name: redis-lb
  namespace: redis
spec:
  ports:
  - name: redis-client
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    argocd.argoproj.io/instance: redis
    redis_setup_type: standalone
    role: standalone
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
